# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e99967200573e3802e15cc292884343075e95e506c8b0a6d70acb3bd84642c32b1632c703668a9e9fa4c21d89658402a0b8e64480b835c1d7cd815e1464a29f

test:
  secret_key_base: 8c68357b5778cee52ec36f15e8cce725c237693548ef8a593472775189dbc14cde1907cfcacf4f93ffc25a2323cb7dd26f9098171fe20251d050c4adb37f352c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
